### ISSUE TITLE
`scripts/update_schema.py` is still for pyright

### ISSUE THREAD

**Issue by jfcherng** [sublimelsp/LSP-basedpyright#2]
Plus, I am not sure whether basedpyright has custom settings that pyright doesn't have.

**Comment by KotlinIsland** [comment]
Basedpyright does have more configuration options that pyright, and are documented here: https://detachhead.github.io/basedpyright/#/?id=new-diagnostic-rules

Additionally, by default, basedpyright has `typeCheckMode = 'all'` as a default.
