### ISSUE TITLE
Broken link to config docs in README

### ISSUE THREAD

**Issue by detly** [sublimelsp/LSP-basedpyright#21]
The root `README.md` has a link to `https://github.com/microsoft/basedpyright/blob/main/docs/configuration.md`, but that results in a 404.

I suspect it should be `https://github.com/DetachHead/basedpyright/blob/main/docs/configuration.md`, but I wasn't sure, hence the issue instead of a PR.

**Comment by jfcherng** [comment]
Thanks. The link you provides is the correct one. Fixed in https://github.com/sublimelsp/LSP-basedpyright/commit/e0cc7b6159291faf909ab7cf03a080f7aa4015f3
