### ISSUE TITLE
 1.2.13 work well and  1.2.14 failure

### ISSUE THREAD

**Issue by maryjeck** [sublimelsp/LSP-basedpyright#32]
the same config
btw:
![图片](https://github.com/user-attachments/assets/e03d3f0e-a333-4d13-a10a-14c623301bd8)

What does this mean?

**Comment by jfcherng** [comment]
Thanks. Fixed in the next release.

**Comment by maryjeck** [comment]
File or directory "\\<default workspace root>" does not exist.

![image](https://github.com/user-attachments/assets/6c861ef5-0b60-4055-a45f-f6a61758fc78)

**Comment by jfcherng** [comment]
doesn't look like our fault.

**Comment by maryjeck** [comment]
and 1.2.15 failure

**Comment by jfcherng** [comment]
my crystall ball failed to guess what "failure" means

**Comment by jfcherng** [comment]
It looks like a upstream bug for single-file mode. will report later

**Comment by maryjeck** [comment]
maybe ,like this
language server crashes when no workspace is open #638 


https://github.com/DetachHead/basedpyright/issues/638

**Comment by jfcherng** [comment]
> maybe ,like this language server crashes when no workspace is open #638
> 
> [DetachHead/basedpyright#638](https://github.com/DetachHead/basedpyright/issues/638)

It's very likely a upstream (pyright) issue since https://github.com/sublimelsp/LSP-pyright/issues/359 is affected by that as well.

**Comment by jfcherng** [comment]
> maybe ,like this language server crashes when no workspace is open #638
> 
> [DetachHead/basedpyright#638](https://github.com/DetachHead/basedpyright/issues/638)

Should be fixed by https://github.com/sublimelsp/LSP-basedpyright/releases/tag/1.2.19
