### ISSUE TITLE
update the default `typeCheckingMode` to `"recommended"`

### ISSUE THREAD

**Issue by DetachHead** [sublimelsp/LSP-basedpyright#44]
thanks for your work maintaining the sublime text basedpyright plugin!

i'm not a sublime text user so i'm not familiar with how language servers work in this editor, but i sometimes use it to try to reproduce language server issues that i can't reproduce in vscode. i noticed that the default `typeCheckingMode` in sublime text is still `"all"`, however in 1.19.0 i've changed the default to the new `"recommended"` ruleset. see https://github.com/DetachHead/basedpyright/releases/tag/v1.19.0

i guess this line just needs to be updated to `"recommended"`:
https://github.com/sublimelsp/LSP-basedpyright/blob/ebfe572a59c42172e62d068abd252c734dfcb02f/LSP-basedpyright.sublime-settings#L77

i can make a PR to do this, but i'm just curious if it's possible to not include these default settings so that they are just picked up from the language server itself, which will reduce the maintenance burden for you in case we make further changes to the default settings in the future

**Comment by jfcherng** [comment]
> So whether we list default settings or not only adds a bit more maintenance.

Sounds like we can just comment out all default settings :D

> We even have a GH workflow that is supposed to mention changes in settings so that we adapt to it while updating to newer version. I'm not sure if that was just an omission in this case or what was the reason.

https://github.com/sublimelsp/LSP-basedpyright/pull/43/files#diff-1b30ef1dc3d227d786b769b6c3fff3c23598512f28d3f2f0379e8c542d4c20a6L1753-L1764

**Comment by rchl** [comment]
> > So whether we list default settings or not only adds a bit more maintenance.
> 
> Sounds like we can just comment out all default settings :D

Well, we can but it helps users to see what is available and what are the defaults. Of course you can get those information through LSP-json but it's not as straightforward and requires a lot of key presses to get descriptions for each option.

So there is benefit to including default options and as long as we have robust syncing solution (which we don't now), it should cause no issues.

> > We even have a GH workflow that is supposed to mention changes in settings so that we adapt to it while updating to newer version. I'm not sure if that was just an omission in this case or what was the reason.
> 
> [#43 (files)](https://github.com/sublimelsp/LSP-basedpyright/pull/43/files#diff-1b30ef1dc3d227d786b769b6c3fff3c23598512f28d3f2f0379e8c542d4c20a6L1753-L1764)

Right, so the schema was updated, only default settings weren't.
